### ISSUE TITLE
Openweathermap returns a 401 error code : Invalid API Key

### ISSUE THREAD

**Issue by vinpav** [kalliope-project/kalliope_neuron_openweathermap#3]
Hi,

The current version of the openweathermap neuron does not work with a free openweathermap account.

The problem comes from the "forecast = owm.daily_forecast(extended_location)" line, as the 16 days/daily forecast API calls requires a paid subscription to openweathermap (take a look at [this chart](https://openweathermap.org/price) for more info).

Currently a free openweathermap subscription gives only access to : 

- Current weather data (urls starting with http://api.openweathermap.org/data/2.5/weather/)
- 5 day / 3 hour forecast (urls starting with http://api.openweathermap.org/data/2.5/forecast/)

It took me quite some time to figure this out, so I tought it was worth mentionning that.
(Thanks for the goob work on Kalliope !)

**Comment by Sispheor** [comment]
It was working, so something changed on their side recently.
I'll take a look, thank you for the hint.

**Comment by Sispheor** [comment]
Can you give a try by adding limit=5 to the line? So we are in free user limit ranges.

**Comment by vinpav** [comment]
Same result with http://api.openweathermap.org/data/2.5/forecast/daily?q=paris&limit=5&appid=XXX
>> {"cod":401, "message": "Invalid API key. Please see http://openweathermap.org/faq#error401 for more info."}

It looks like http://api.openweathermap.org/data/2.5/forecast/daily is forbidden to free accounts.

**Comment by Sispheor** [comment]
OK, I'll see with the lib owner if we have a workaround for this. 
I can see that we are not using the last version. Maybe is already handled in the last version.

**Comment by Sispheor** [comment]
Seems an issue on the API. 
Do you have the same issue as [this one](https://github.com/csparpa/pyowm/issues/237)?

**Comment by vinpav** [comment]
Yes, it's the same issue. But again, I don't think this must be considered like a bug because the API response with a free account fits the price chart on the openweathermap website.
16 days/daily forecast API = http://api.openweathermap.org/data/2.5/forecast/daily = owm.daily_forecast(...) = requires a paid subscription.
(But, I might be misunderstanding)
Anyway, I'd be happy if there's a way to make this work with a free account ;)

**Comment by Sispheor** [comment]
ok. I don't see any workaround to get the "tomorrow" weather with the lib. 
I'm not sure this is handled so far.

**Comment by vinpav** [comment]
According to what I've seen in the API, there is a solution to get some detailed forecast information for the next 5 days.

Using the "5 days/3 hour forecast API", available with a free account, you can get the 5 next days forcast by 3 hours periods. With good python skills (which I don't have), it might be possible to regroup all these data day by day and compute the results : day X pressure = average pressure for that day, day X min temperature = min temperature for that day, day X precipitations = sum of precipitations for that day, etc.
Though, it seems to represent a rather huge effort for a result that would probably not be fully satisfying.

For now I've just commented the "tommorow" part of the neuron to make the "today" weather work.
Thanks for the feedback on this issue !

**Comment by Sispheor** [comment]
Yes, I know that it's possible to request on the api directly. The fact is taht we are using a lib to facilitate this step.
And the idea is to stick on this lib. My question was, is the lib aware of this potential change? Do we have another call that can do the trick?
I'll check this when I have time. 

Thanks for pointing out the issue.

**Comment by Sispheor** [comment]
Current weather and forecast ok.
Neuron updated.

**Comment by vinpav** [comment]
Same problem with V2 update of this neuron : 

> pyowm.exceptions.api_response_error.UnauthorizedError: Your API subscription level does not allow to perform this operation
> Reason: Invalid API Key provided

I'm still using a free API key. Am I missing something ?

**Comment by Sispheor** [comment]
Show us your synapse. (Cut some letters of your key)

**Comment by vinpav** [comment]
```
- name: "weather-summary"
  signals:
      - order: "quel temps fait il"
  neurons:
      - openweathermap:
          api_key: "25xxxxxxxxxxxxxxxxxxxxxxbaa"
          lang: "fr"
          temp_unit: "celsius"
          location : "paris"
          country: "FR"
          say_template:
              - "Actuellement à {{ location }} : {{ current['weather_status'] }} avec une température de {{ current['temp'] }} degrés."
```

**Comment by Sispheor** [comment]
looks good.
weird, no typo in the api key? a space or something?

**Comment by daylicron** [comment]
I can confirm the issue.
Exception in kalliope debug log on pastebin: https://pastebin.com/5T6iZevb

I'm using up to date pyown version 2.6.1 from pip:
``pip install pyowm
Requirement already satisfied: pyowm in /usr/local/lib/python3.6/dist-packages (2.6.1)``

My synapse:

```
   - name: "getthe-weather"
     signals:
       - order: "Wie wird das Wetter"
       - order: "Wie ist das Wetter"
       - order: "Wie ist das Wetter heute"
     neurons:
       - openweathermap:
           api_key: "e9ecxxxxxxxxxxxxxxxxxxxxxxxxe2d6"
           lang: "de"
           temp_unit: "celsius"
           location: "Berlin"
           country: "DE"
           say_template:
           - "Heute wird das Wetter {{ weather_today }} bei einer Temperatur von {{ temp_today_temp }} Grad."
```
